jobs:
- name: concourse-trial-publish-b
  public: true
  serial: true
  plan:
  - get: concourse-trial
    trigger: true
  - put: concourse-trial-docker-image-b
    params:
      build: concourse-trial/b

resources:
- name: concourse-trial
  type: git
  source:
    uri: https://github.com/topiaruss/concourse-trial.git

- name: concourse-trial-docker-image-b
  type: docker-image
  source:
    email: {{quay_io-email}}
    username: {{quay_io-username}}
    password: {{quay_io-password}}
    repository: quay.io/russf/concourse-trial-b

