jobs:
- name: concourse-trial-publish-a
  public: true
  serial: true
  plan:
  - get: concourse-trial
  - put: concourse-trial-docker-image
    params:
      build: concourse-trial/a

resources:
- name: concourse-trial
  type: git
  source:
    uri: https://github.com/topiaruss/concourse-trial.git

- name: concourse-trial-docker-image-a
  type: docker-image
  source:
    email: {{quay_io-email}}
    username: {{quay_io-username}}
    password: {{quay_io-password}}
    repository: quay.io/russf/concourse-trial-a


