# Default values for contrialchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
alpha:
  name: alpha
  replicaCount: 1
  image:
    name: quay.io/russf/concourse-trial-alpha
    tag: latest
beta:
  name: beta
  replicaCount: 3
  image:
    name: quay.io/russf/concourse-trial-beta
    tag: latest
gamma:
  name: gamma
  replicaCount: 3
  image:
    name: quay.io/russf/concourse-trial-gamma
    tag: latest
service:
  name: nginx
  type: ClusterIP
  externalPort: 80
  internalPort: 80
ingress:
  enabled: false
antiAffinity: soft
